# Generated by Django 4.2.20 on 2025-04-24 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=80, verbose_name='Nome')),
                ('marca', models.CharField(blank=True, max_length=80, verbose_name='Marca')),
                ('categoria', models.CharField(blank=True, max_length=80, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(default=0, null=True, verbose_name='Ano')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Preço')),
                ('acessorios', models.ManyToManyField(blank=True, to='garagem.acessorio', verbose_name='Acessórios')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garagem.cor', verbose_name='Cor')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garagem.modelo', verbose_name='Modelo')),
            ],
        ),
    ]
