# Generated by Django 4.2.23 on 2025-06-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0002_veiculo_capa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'ordering': ['nome'], 'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
        migrations.AlterField(
            model_name='cor',
            name='nome',
            field=models.CharField(max_length=40, verbose_name='Cor'),
        ),
    ]
