# Generated by Django 4.2.23 on 2025-06-11 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0005_itenscompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='tipo_pagamento',
            field=models.IntegerField(choices=[(1, 'Cartão de Crédito'), (2, 'Cartão de Débito'), (3, 'PIX'), (4, 'Boleto'), (5, 'Transferência Bancária'), (6, 'Dinheiro'), (7, 'Outro')], default=1),
        ),
    ]
